# tracking_params.yaml

# Subscriber topics
image_subscriber: "/camera/image/undistorted"
object_detection_subscriber: "/object_detection/object"
sign_detection__subscriber: "/object_detection/sign"

# Publisher topics
object_tracking_publisher: "/object_tracking/tracked_objects"
sign_tracking_publisher: "/sign_tracking/tracked_signs"

# Parameters
state: 1         # NodeState.ACTIVE.value (ersetze ggf. mit deinem tatsächlichen Enum-Wert)
debug: false

# Common parameters
dt: 0.1
max_x: 5000.0
max_y: 3000.0

# Object tracker parameters (moving objects)
object_max_age: 20
object_min_hits: 3
object_min_age: 3
object_max_distance: 9.21
object_q_pos: 50.0
object_q_vel: 100.0
object_r_pos: 100.0
object_sigma_pos_init: 500.0
object_sigma_vel_init: 1000.0

# Sign tracker parameters (static objects)
sign_max_age: 20
sign_min_hits: 2
sign_min_age: 2
sign_max_distance: 9.21
sign_q_pos: 25.0
sign_q_vel: 50.0
sign_r_pos: 100.0
sign_sigma_pos_init: 300.0
sign_sigma_vel_init: 500.0